name = "my-blog"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "8b3d3733-28a4-455f-bfe8-0a7400ad86fe"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
